net:
  proxy:
    # 代理相关信息
    - ip: 127.0.0.1
      port: 1080
      type: SOCKS

ai:
  maxNum:
    basic: 5 # 默认兜底策略
    wechat: 10 # 公众号用户
    star: 100 # 星球用户
    starTry: 30 # 星球用户
    invited: 0.1 # 被邀请
    inviteNum: 0.2 # 邀请人数执行策略
    starNumber: 4000 # 目前为 4000
    historyContextCnt: 10 # 多轮对话上下文的条数，默认最多给10条
  source: # 支持的AI模型
    - CHAT_GPT_3_5
    - CHAT_GPT_4
    - PAI_AI
    - XUN_FEI_AI



