rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: admin
  passport: admin
  virtualhost: /
  switchFlag: false
  pool_size: 10  # 连接池大小：10个消费者 + 5个发布缓冲
  consumerCount: 8  # 消费者数量，根据用户规模调整
  processorThreads: 20  # 消息处理线程数，根据CPU核心数调整
