view:
  site:
    wxPayEnable: ${wx.pay.enable}
    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
    needPayArticleReadCount: 20 # 付费文章，未付费可以看到的文章内容
    websiteName: TecHub
#    websiteLogoUrl: https://paicoding.com/img/icon.png
#    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
    websiteLogoUrl: https://cdn.jsdelivr.net/gh/JakicDong/blog-assets@main/images/logo.png
    websiteFaviconIconUrl: https://cdn.jsdelivr.net/gh/JakicDong/blog-assets@main/images/logo.png
# https://cdn.jsdelivr.net/gh/JakicDong/blog-assets@main/images/logo.png
#    https://github.com/JakicDong/blog-assets/blob/main/images/logo.png
    zsxqUrl: https://paicoding.com/article/detail/314
#    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
    zsxqPosterUrl: https://cdn.jsdelivr.net/gh/JakicDong/blog-assets@main/images/logo.png

    contactMeTitle: 联系我 - JakicDong
    contactMeWxQrCode: https://cdn.jsdelivr.net/gh/JakicDong/blog-assets@main/images/JakicfuwuhaoQr1.jpg
    contactMeStarQrCode: https://cdn.jsdelivr.net/gh/JakicDong/blog-assets@main/images/JakicfuwuhaoQr1.jpg
    pageSize: 20
    cdnImgStyle:
    websiteRecord: TecHub
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到TecHub，戳<a href="/article/detail/15">全方位视角解读</a>了解我们
    oss: